### ISSUE TITLE
What are the "group" and "role" settings for?

### ISSUE THREAD

**Issue by FredrikFornstad** [warmcat/lws-esp32-factory#31]
Sorry if I have missed some readme information, but I have tried to understand the "group" and "role" parameters/settings and how they are used (what is the meaning of them...) in the example code.

In some parts it seems that it is some sort of remainings from an earlier version of the code, but then again I can see that they are in use in various places. While I can imagine/guess a few different "use cases", I thought it might be easier just to ask.

**Comment by lws-team** [comment]
This stuff is incomplete, but the general scenario is a situation where you have multiple devices that are working on the same thing.  For example if you were working on an embedded device, maybe two or three measures power in different rails, one proxies to a TTL serial port over ssh, one switches IO in and out for automated testing.

All of those devices would be in one self-assembling "group".  Other similar setups to different boards would be in a different "group".  Devices within a group find each other by mdns.

The destination point of all this ultimately the group members will have a "leader", which along with its other duties can proxy payload data to the other group members.  You only have to accept the one tls certificate of the leader and operate through him, to see and control data from all the group members.  This is different from the usual IoT concept where the group members push their stuff to an external cloud server and you get it from there.  The data remains on your local network.

I have an implementation where each group member shows an iframe with the content of the other group members if you connect to it.  But this does not work because you have to had accepted the tls certs of every member, it's too cumbersome.  Hence the idea of a proxying single "group leader".

However to do this the leader has to be able to accept many incoming tls client connections, none of which carry much data in the usual case.  So work on this is blocked while I created the patches for mbedTLS that allow dynamic buffer sizing; this reduces the typical cost of a tls connection carrying small payloads to around 4KiB from 32KiB.

https://github.com/lws-team/mbedtls/commits/dynamic-ssl-buffers

But I did not reckon on mbedTLS' owners, Arm, simply not accepting any external contribution, from anyone.

https://github.com/ARMmbed/mbedtls/pull/1208

**Comment by FredrikFornstad** [comment]
Thanks for a good explanation. Now I know.
